name: first-test
on: push
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World!"
  job-two:
    runs-on: ubuntu-22.04
    steps:
      - name: second-step
        run: echo "Hello World2!"
