name: first-test
on: 
      push :
            branches:
              - main
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  job-two:
    runs-on: ubuntu-22.04
    steps:
      - name: second-step
        run: echo "Hello World!"
